[package]
name = "spin-sqlite-libsql"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
# We don't actually use rusqlite itself, but we'd like the same bundled
# libsqlite3-sys as used by spin-sqlite-inproc.
libsql = { version = "0.5", features = ["remote"], default-features = false }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-world = { path = "../world" }
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
