[build]
default-target = "x86_64-unknown-linux-musl"

[build.env]
passthrough = ["BUILD_SPIN_EXAMPLES", "RUSTFLAGS"]

[target.aarch64-unknown-linux-musl]
dockerfile.file = "./cross/Dockerfile"
dockerfile.context = "./cross/"
