spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "An application that returns the arguments the program started with, the environment variables set, and current time"
name = "wagi-hello-world"
version = "1.0.0"

[[trigger.http]]
route = "/env"
component = "env"
executor = { type = "wagi" }

[component.env]
source = "target/wasm32-wasip1/release/wagihelloworld.wasm"
[component.env.build]
command = "cargo build --target wasm32-wasip1 --release"
