[package]
name = "spin-trigger-redis"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
redis = { version = "0.27", features = ["tokio-comp"] }
serde = { workspace = true }
spin-factor-variables = { path = "../factor-variables" }
spin-factors = { path = "../factors" }
spin-telemetry = { path = "../telemetry" }
spin-trigger = { path = "../trigger" }
spin-world = { path = "../world" }
tokio = { workspace = true, features = ["macros", "rt"] }
tracing = { workspace = true }

[lints]
workspace = true
