manifest_version = "1"
id = "http-grain"
description = "HTTP request handler using Grain"
tags = ["http", "grain"]

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }
