[net]
git-fetch-with-cli = true

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+fp16"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+fp16", "-C", "target-feature=+crt-static", "-C", "link-self-contained=yes"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-self-contained=yes"]

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
