manifest_version = "1"
id = "static-fileserver"
description = "Serves static files from an asset directory"
trigger_type = "http"
tags = ["http", "file", "static", "asset"]

[add_component]
skip_files = ["spin.toml", ".gitignore"]
skip_parameters = ["project-description"]
[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
http-path = { type = "string", prompt = "HTTP path", default = "/static/...", pattern = "^/\\S*$" }
files-path = { type = "string", prompt = "Directory containing the files to serve", default = "assets", pattern = "^\\S+$" }

[outputs]
create_asset_directory = { action = "create_dir", path = "{{ files-path }}", at = "manifest" }
