[package]
name = "deny-all"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.28.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "fermyon:spin-virt"

[package.metadata.component.target]
world = "deny-all"

[package.metadata.component.target.dependencies]
"fermyon:spin" = { path = "wit/deps/fermyon/spin.wasm" }
"wasi:filesystem" = { path = "wit/deps/wasi/filesystem.wasm" }
"wasi:sockets" = { path = "wit/deps/wasi/sockets.wasm" }
"wasi:clocks" = { path = "wit/deps/wasi/clocks.wasm" }
"wasi:http" = { path = "wit/deps/wasi/http.wasm" }
"wasi:cli" = { path = "wit/deps/wasi/cli.wasm" }
"wasi:io" = { path = "wit/deps/wasi/io.wasm" }

[workspace]
