[package]
name = "vault-variable-test"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Vault Application Variable Provider Example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
constant_time_eq = "0.3.0"
spin-sdk = "2.2.0"

[workspace]
