manifest_version = "1"
id = "redirect"
description = "Redirects a HTTP route"
trigger_type = "http"
tags = ["redirect"]

[add_component]
skip_files = ["spin.toml"]
skip_parameters = ["project-description"]
[add_component.snippets]
component = "component.txt"

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
redirect-from = { type = "string", prompt = "Redirect from", pattern = "^/\\S*$" }
redirect-to = { type = "string", prompt = "Redirect to" }
