manifest_version = "1"
id = "http-empty"
description = "HTTP application with no components"
tags = ["http"]

[parameters]
project-description = { type = "string",  prompt = "Description", default = "" }
