spin_manifest_version = 2

[application]
authors = ["itowlson <ivan.towlson@fermyon.com>"]
name = "goodbye"
version = "0.1.0"

[application.trigger.timer]
speedup = 2

[[trigger.timer]]
interval_secs = 6
component = "three"

[[trigger.timer]]
interval_secs = 10
component = "five"

[component.three]
source = "target/wasm32-wasip1/release/timer_app_example.wasm"
[component.three.variables]
message = "Fizz"
[component.three.build]
command = "cargo build --target wasm32-wasip1 --release"

[component.five]
source = "target/wasm32-wasip1/release/timer_app_example.wasm"
[component.five.variables]
message = "Buzz"
[component.five.build]
command = "cargo build --target wasm32-wasip1 --release"
