name: Check tags for templates
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check-tags:
    name: check tags
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'fermyon' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ## this ensures we fetch all tags and branches
          fetch-depth: 0 

      - name: Check tags
        run: .github/gh-checktags.sh
